### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Bilbo77--Primer-trabajo-en-equipo-Instagram#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo. Felicidades @Bilbo77  !
## Estilo de código y limpieza
- ¡Muy bien hecho!
## Mejores prácticas/comentarios
- En el styles.css, en la regla CSS para el cuerpo del documento (body), el valor font-style: normal; no es necesario, ya que font-style se utiliza para establecer la cursiva o normalidad del texto, y por defecto es normal. Puedes quitarlo sin problema.

**Comment by Bilbo77** [comment]
Oído cocina! El valor "normal" ya está predefinido así que si no fuera a cambiar el "font-style" no tiene sentido reiterar que es normal.

**Comment by EduardoHernandezGuzman** [comment]
🆗
